# -*- coding: utf-8 -*-
"""GB_les_4_task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1biLtRnnW8A4HnMyc1CRnPragI4Esy9t0

1. Проанализировать скорость и сложность одного любого алгоритма из разработанных в рамках домашнего задания первых трех уроков.

Примечание. Идеальным решением будет:

a. выбрать хорошую задачу, которую имеет смысл оценивать,

b. написать 3 варианта кода (один у вас уже есть),

c. проанализировать 3 варианта и выбрать оптимальный,

d. результаты анализа вставить в виде комментариев в файл с кодом (не забудьте указать, для каких N вы проводили замеры),

e. написать общий вывод: какой из трёх вариантов лучше и почему.

Lesson 3. Task 6. В программе генерируется случайное целое число от 0 до 100. Пользователь должен его отгадать не более чем за 10 попыток. После каждой неудачной попытки должно сообщаться, больше или меньше введенное пользователем число, чем то, что загадано. Если за 10 попыток число не отгадано, вывести ответ.
"""

# Commented out IPython magic to ensure Python compatibility.
from random import random 
a1 = 0 
a2 = 100
x = int(random () * (a2 - a1 +1)) + a1 
count = 1
while count<=10: 
  a = int(input("У вас 10 попыток. Введите предполагаемое число: "))
  if a>x:
     print ("много")
  elif a<x:
     print ("мало")
  else:
     print ("число угадано")
     break 
  count += 1
else:
 print ("попытки исчерпаны, загаданное число = ", x)
# %timeit (a)
#10000000 loops, best of 3: 20.4 ns per loop
# %prun (a) 
#  3 function calls in 0.000 seconds

   #Ordered by: internal time

   #ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        #1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        #1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        #1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

# Commented out IPython magic to ensure Python compatibility.
import random 
x = random.randint(0,100)
print ("У вас 10 попыток, чтобы отгадать число от 0 до 100")
for i in range(1, 11):
  a = int(input("Попытка: "))
  if x < a:
    print ("много")
  elif x > a:
    print ("мало")
  else:
    print ("вы угадали с попытки ", i)
    break
else:
  print ("попытки исчерпаны, загаданное число = ", x)
# %timeit (a)
#10000000 loops, best of 3: 19.9 ns per loop

# %prun (a)
#3 function calls in 0.000 seconds

   #Ordered by: internal time

   #ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        #1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        #1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        #1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}